name: Full CI-CD Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    # 🔹 Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # 🔐 Docker login (needed for push)
    - name: Login DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 🐳 Build & Push Backend
    - name: Build backend
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:v1 ./backend
        docker push ${{ secrets.DOCKER_USERNAME }}/backend:v1

    # 🐳 Build & Push Frontend
    - name: Build frontend
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:v1 ./frontend
        docker push ${{ secrets.DOCKER_USERNAME }}/frontend:v1

    # 📁 COPY docker-compose.yml + .env TO EC2 (🔥 IMPORTANT)
    - name: Copy files to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "docker-compose.yaml,.env"
        target: "/home/ec2-user/"

    # 🚀 DEPLOY
    - name: SSH Deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ec2-user

          echo "📂 Files in EC2:"
          ls -l

          # install docker if missing
          if ! command -v docker &> /dev/null
          then
            sudo yum update -y
            sudo yum install -y docker
            sudo systemctl start docker
            sudo usermod -aG docker ec2-user
          fi

          # install docker compose
          if ! docker compose version &> /dev/null
          then
            sudo mkdir -p /usr/local/lib/docker/cli-plugins
            sudo curl -SL https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64 \
            -o /usr/local/lib/docker/cli-plugins/docker-compose
            sudo chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
          fi

          # verify
          docker compose version

          # pull latest images
          docker compose -f docker-compose.yml pull

          # restart containers
          docker compose -f docker-compose.yml up -d --remove-orphans